mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.cuiyq.mybatis.entity
server:
    port: 8080
spring:
    application:
        name: user-center

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: cuiyq
        password: 123456
        url: jdbc:mysql://120.55.125.187:3306/cuiyq
