mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.cuiyq.mybatis.entity
server:
    port: 8080
spring:
    application:
        name: user-center
    session:
        timeout: 86400

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: cuiyq
        password: 123456
        url: jdbc:mysql://120.55.125.187:3306/cuiyq

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false
    global-config:
        db-config:
            logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
            logic-delete-value: 1 # 逻辑已删除值(默认为 1)
            logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
