spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: user_center_prod1
        password: 1234561
        url: jdbc:mysql://120.55.125.187:3306/user_center_prod
server:
    address: 0.0.0.0
